apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis04
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis04
    type: Directory
  nodeAffinity:
    required:
      - nodeSelectorTerms:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
