apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: gop-fs-service
  name: gop-fs-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31007
  selector:
    name: gop-file-server
  type: NodePort
status:
  loadBalancer: {}
