apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db-deployment
  name: db-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db-deployment
    spec:
      volumes:
        - name: db-data
          emptyDir: {}
      containers:
        - image: postgres:9.4
          name: postgres
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRESQL_USER
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          resources: {}
          ports:
            - containerPort: 5432
status: {}
