apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-deployment
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db-deployment
status:
  loadBalancer: {}
